name: sepcommander
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip:
      - numpy
      - lightning
      - tensorboard
      - librosa
      - torchlibrosa
      - transformers
      - optimum
      - ftfy
      - braceexpand
      - wget
      - pandas
      - webdataset
      - pyloudnorm
      - audiocaps-download
      - h5py
  - torchaudio
  - torchvision