---
task_name: AudioSep

data:
    train_datafiles:
        - 'config/datafiles/audiocaps_train_mix.json'
    val_datafiles:
        - 'config/datafiles/audiocaps_val_mix.json'
    test_datafiles:
        - 'config/datafiles/audiocaps_test_mix.json'

    sampling_rate: 32000
    segment_seconds: 10
    loudness_norm:
        lower_db: -10
        higher_db: 10
    max_mix_num: 2
    is_premixed: true

model:
    query_net: CLAP
    condition_size: 256
    use_text_ratio: 1.0

    model_type: ResUNet30
    input_channels: 1
    output_channels: 1
    resume_checkpoint: ""
    only_train_film: true

train:
    optimizer:
        optimizer_type: AdamW
        learning_rate: 1e-3
        warm_up_steps: 10000
        reduce_lr_steps: 1000000
        lr_lambda_type: constant_warm_up
    num_nodes: 1
    num_workers: 1
    loss_type: l1_wav
    sync_batchnorm: True
    batch_size_per_device: 6
    save_step_frequency: 3000  # Save every #save_step_frequency steps.
    checkpoint_path: null # checkpoint/audiosep_base_4M_steps.ckpt # workspace/AudioSep/checkpoints/train/sepcommands_base,devices=1/step=18000_no_pretrain.ckpt
    n_epochs: 10

accelerator: gpu
device: null
